#!/bin/bash --

NAME=draft-kerwin-file-scheme
VERSION=05

xmllint $NAME.xml --loaddtd --noent > $NAME-latest.xml
echo "Generated $NAME-latest.xml"

xsltproc -o $NAME-latest.html --path ".:lib" rfc2629.xslt $NAME-latest.xml
echo "Generated $NAME-latest.html"

sed -e 's/ x:maturity-level="draft"//' \
	-e 's/ xmlns:x="http:\/\/purl\.org\/net\/xml2rfc\/ext"//' \
	-e 's/<x:feedback .*>//' \
	-e "s/$NAME-latest/$NAME-$VERSION/" \
	< $NAME-latest.xml > $NAME-$VERSION.xml
echo "Generated $NAME-$VERSION.xml"

